### ISSUE TITLE
Marauder agent does not build on default installation in EC2 Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by agithubuserlol** [FactionC2/Faction#1]
**Describe the bug**
The default installation of FactionC2 does not allow you to build a Marauder payload with the default HTTP Transport.

 **Error Message** 
```Timestamp: 2019-03-21T18:17:19.303250

Source: .NET Build Server

Message: Error building Marauder

Details


Stdout: 
Stderr: bash: ./Transports/DIRECT/build.sh: No such file or directory
```

**To Reproduce**
1. Launch a new EC2 Ubuntu 18.04.2 LTS instance. Free tier is fine.
2. Execute:
```
git clone https://github.com/FactionC2/Faction/
cd install
sudo bash ./install.sh
```
3. Execute `sudo faction setup`
4. Authenticate to FactionC2 console.
5. Navigate to the Payloads tab.
6. Select New Payload.
7. Set agent type to Marauder.
8. Set transport type to Direct Transport. Set format to .NET 3.5 Executable (or with debug, same results)
9. Click Create Payload.
10. Receive error above.

**Desktop (please complete the following information):**
lsb_release -a:
```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Additional context**
Excited. Hope I didn't miss something obvious =)

Attempted `sudo faction clean --all` and subsequent `sudo faction setup`. No errors of any relevance, just a user warning that I don't believe is related:
```
/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
```

**Comment by highmeh** [comment]
+1 on this. For the record, I've attempted this on three versions of Ubuntu: 18.04.02 (Local version on VBox; version that was specified in the docs), 18.04.01 (Linode), and the newest LTS build of 18.10 (Linode). Same result on each version.

Setup goes fine with the exception of the warning @agithubuserlol mentioned during install, about a name change. Login goes fine. Creating a payload shows: "ERROR: Error building Marauder [GO]" - when GO is clicked, it returns the following error:

`Timestamp: 2019-03-22T21:02:50.776662

Source: .NET Build Server

Message: Error building Marauder

Details


Stdout: 
Stderr: bash: ./Transports/DIRECT/build.sh: No such file or directory
`
Entering the docker container, I found the directory I think it's running from (/opt/faction/agents/Marauder/maraudershell-Marauder-9a17efd) which does have a ./Transports/DIRECT/build.sh file. When I run that file on its own, in the command line, I get the same error. Looking at exploring two potential avenues: The process executing when creating a payload is in the wrong relative directory, or theres a file with a BOM issue somewhere trying to execute build.sh. These may be completely wrong, just spitballing here.

**Comment by drhbonkers** [comment]
Confirmed there are a few issues building the HttpTransport module, will fix this weekend.

**Comment by jaredhaight** [comment]
The fact that it's sitting in /opt/faction/agents/Marauder/
maraudershell-Marauder-9a17efd is unexpected. It should just be
/opt/faction/agents/Marauder

If I had to guess, I'd think the issue here is that the build server is
running build.sh from /opt/faction/agents/Marauder (as it should), and the
extra folder is throwing everything off.

So the actual fix here would be to check out the download repo function in
the CLI and see why it's putting it in that weird folder. That function is
under processing/faction/repo.py (I believe)

I'm on vacation this next week, and if I open an IDE my wife will murder
me. If anyone wants to dig in on the above and see if that fixes it, have
fun. Else I can take a look at it when I'm back.

Assuming the above is correct, a short term fix would be to move the
marauder files up a directory.

**Comment by jaredhaight** [comment]
Giving this some more thought, I remember I had to add some steps to account for this already and apparently that's not working here. 

I forget what my original reasoning was for downloading and unzipping the repos instead of just cloning them, but this seems like a pain in the ass and we should just call git from the CLI to grab Marauder and the Modules-Dotnet repo. That will have the added advantage of being able to update the installs by just running git pull.

**Comment by jaredhaight** [comment]
Alright, this should be fixed. Switched [the install script](https://github.com/FactionC2/Faction/commit/5206ccea01e71a563dc99c3e0c9d57aa7eb854d6) and [the CLI](https://github.com/FactionC2/CLI/commit/23f505036a4792d9e86076a6d294e1537e5d4354) to use git to pull the repos instead of dorking around with the zip files. You should be able to update to the new versions by running:

```
faction clean --all
rm -rf /opt/faction
```

Then git pull and run the new install script or run `curl https://raw.githubusercontent.com/FactionC2/Faction/master/install.sh | sudo bash`

This has been tested on Linode, and I'm assuming it'll work on AWS as well. Feel free to reopen this issue if there are further problems
