### ISSUE TITLE
New Transport name is left blank when created in console.

### ISSUE THREAD

**Issue by highmeh** [FactionC2/Faction#5]
**Describe the bug**
When creating a new Transport on the Faction Console, the name is left blank. Only the description field is added.

** Error Message **
None

**To Reproduce**
1. Log into Faction as the Admin user.
2. Click on Transports
3. Click on New
4. Create a Transport with any description desired
5. A transport is created without a name, but with a description, API, Created value, etc. as expected.
6. Interact with the Postgres docker container using "sudo docker exec -it <container> /bin/bash"
7. su to the postgres user
8. Log into postgres: $ /usr/lib/postgresql/11/bin/psql faction postgres
9. Run the query:# SELECT * FROM "Transport";
10. Note that the Name field is blank for the transport you created above
11. Run the query: `# UPDATE "Transport" SET "Name" = 'YourTransportName' WHERE "Transport"."Id" = 2;`
12. Refresh the console; the name field is now populated

**Expected behavior**
A name field should be displayed on the Transport creation dialog box, which then populates the Transport Table's "Name" field. Alternately, a name could be auto-generated as is done with payload and agent names.

**Desktop (please complete the following information):**

Ubuntu 18.04.2 LTS \n \l
Linux factionc2 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jaredhaight** [comment]
This is actually by design, but its an understandable point of confusion. The idea is that the name is just the Transport type ("HTTP", "DNS", "Franks Leet IMCP Transport method", whatever) and the Transport should provide this name when it registers with Faction. So the process would be:

1. User creates a new transport in the Faction console, giving it a description.
2. Faction creates a new record for the transport, and a new api key for the transport to use. It gives the user the: Transport ID number, the transport api key name, and the api key secret.
3. User provides this information to the Transport server, the Transport server registers with Faction, providing its: Name and Configuration details.

As part of the ramp up to beta, where going to rename "Name" to "Transport Type", and "Description" to "Name". I *think* this makes more sense. The user names the transport, the transport tells us what type it is when it registers.

**Comment by jaredhaight** [comment]
This has been fixed
